In [ ]:
#importing libraries
from math import sqrt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
#dataset
dataset = sns.load_dataset("iris")
#dataset.species.unique() => ['setosa', 'versicolor', 'virginica']
dataset['species']= dataset["species"].map({"setosa": 1, "versicolor": 2,"virginica":3})
display(dataset)
print("\n\n\n\n")
training_data, testing_data = train_test_split(dataset, test_size=0.2, random_state=25)
testing_data1  = testing_data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

results = pd.DataFrame()
results['Observed'] = testing_data['species']
results['Predicted']= np.NaN 
results = results.reset_index()

display(training_data)
print("\n\n\n\n")
display(testing_data1)

training_data1  = training_data.copy(deep=True).values.tolist()
testing_data2  = testing_data1.copy(deep=True).values.tolist()


sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        1
1             4.9          3.0           1.4          0.2        1
2             4.7          3.2           1.3          0.2        1
3             4.6          3.1           1.5          0.2        1
4             5.0          3.6           1.4          0.2        1
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        3
146           6.3          2.5           5.0          1.9        3
147           6.5          3.0           5.2          2.0        3
148           6.2          3.4           5.4          2.3        3
149           5.9          3.0           5.1          1.8        3

[150 rows x 5 columns]

sepal_length  sepal_width  petal_length  petal_width  species
54            6.5          2.8           4.6          1.5        2
113           5.7          2.5           5.0          2.0        3
135           7.7          3.0           6.1          2.3        3
4             5.0          3.6           1.4          0.2        1
115           6.4          3.2           5.3          2.3        3
..            ...          ...           ...          ...      ...
118           7.7          2.6           6.9          2.3        3
61            5.9          3.0           4.2          1.5        2
143           6.8          3.2           5.9          2.3        3
62            6.0          2.2           4.0          1.0        2
132           6.4          2.8           5.6          2.2        3

[120 rows x 5 columns]

sepal_length  sepal_width  petal_length  petal_width
28            5.2          3.4           1.4          0.2
72            6.3          2.5           4.9          1.5
70            5.9          3.2           4.8          1.8
85            6.0          3.4           4.5          1.6
128           6.4          2.8           5.6          2.1
65            6.7          3.1           4.4          1.4
127           6.1          3.0           4.9          1.8
42            4.4          3.2           1.3          0.2
81            5.5          2.4           3.7          1.0
93            5.0          2.3           3.3          1.0
21            5.1          3.7           1.5          0.4
31            5.4          3.4           1.5          0.4
26            5.0          3.4           1.6          0.4
133           6.3          2.8           5.1          1.5
6             4.6          3.4           1.4          0.3
58            6.6          2.9           4.6          1.3
125           7.2          3.2           6.0          1.8
139           6.9          3.1           5.4          2.1
64            5.6          2.9           3.6          1.3
94            5.6          2.7           4.2          1.3
79            5.7          2.6           3.5          1.0
99            5.7          2.8           4.1          1.3
66            5.6          3.0           4.5          1.5
20            5.4          3.4           1.7          0.2
34            4.9          3.1           1.5          0.2
117           7.7          3.8           6.7          2.2
69            5.6          2.5           3.9          1.1
122           7.7          2.8           6.7          2.0
120           6.9          3.2           5.7          2.3
41            4.5          2.3           1.3          0.3

In [ ]:
# calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return sqrt(distance)

# Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
	distances = list()
	for train_row in train:
		dist = euclidean_distance(test_row, train_row)
		distances.append((train_row, dist))
	distances.sort(key=lambda tup: tup[1])
	neighbors = list()
	for i in range(num_neighbors):
		neighbors.append(distances[i][0])
	return neighbors

# Make a classification prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
	neighbors = get_neighbors(train, test_row, num_neighbors)
	output_values = [row[-1] for row in neighbors]
	prediction = max(set(output_values), key=output_values.count)
	return prediction

In [ ]:
k = int(input())

10


In [ ]:
for ii in range(0,len(testing_data2)):
    results['Predicted'][ii] = predict_classification(training_data1, testing_data2[ii], k)


results1  = results.copy(deep=True)

results['Observed']= results["Observed"].map({1:"setosa", 2:"versicolor",3:"virginica"})
results['Predicted']= results["Predicted"].map({1:"setosa", 2:"versicolor",3:"virginica"})

results

<ipython-input-6-6572826228d9>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  results['Predicted'][ii] = predict_classification(training_data1, testing_data2[ii], 4)


index    Observed   Predicted
0      28      setosa      setosa
1      72  versicolor   virginica
2      70  versicolor  versicolor
3      85  versicolor  versicolor
4     128   virginica   virginica
5      65  versicolor  versicolor
6     127   virginica   virginica
7      42      setosa      setosa
8      81  versicolor  versicolor
9      93  versicolor  versicolor
10     21      setosa      setosa
11     31      setosa      setosa
12     26      setosa      setosa
13    133   virginica   virginica
14      6      setosa      setosa
15     58  versicolor  versicolor
16    125   virginica   virginica
17    139   virginica   virginica
18     64  versicolor  versicolor
19     94  versicolor  versicolor
20     79  versicolor  versicolor
21     99  versicolor  versicolor
22     66  versicolor  versicolor
23     20      setosa      setosa
24     34      setosa      setosa
25    117   virginica   virginica
26     69  versicolor  versicolor
27    122   virginica   virginica
28    120   virginica   virginica
29     41      setosa      setosa

In [ ]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print("Confusion matrix:\n",confusion_matrix(results1['Observed'], results1['Predicted']))


# Accuracy
from sklearn.metrics import accuracy_score
print("\n\naccuracy score :\n",accuracy_score(results1['Observed'], results1['Predicted']))


from sklearn.metrics import f1_score
print("\n\nf1 score:\n",f1_score(results1['Observed'], results1['Predicted'], average=None),"\n\n\n")


from sklearn.metrics import classification_report
print(classification_report(results1['Observed'], results1['Predicted'])) #, target_names=target_names))


Confusion matrix:
 [[ 9  0  0]
 [ 0 12  1]
 [ 0  0  8]]


accuracy score :
 0.9666666666666667


f1 score:
 [1.         0.96       0.94117647] 



              precision    recall  f1-score   support

           1       1.00      1.00      1.00         9
           2       1.00      0.92      0.96        13
           3       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

